### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by command76** [lmerotta/phpokeapi#2] opened 2019-03-29 00:52 UTC
I am new to PHP and am not too familiar with classes and namespaces.  I installed the required files using composer and entered the information to instantiate a new class of Client but for some reason after entered the use keyword with the correct information and creating the variable for the new class I get this error:  
Uncaught Error: Class 'PokeAPI\Client' not found in /Applications/AMPPS/www/assignment3.com/index.php:4 Stack trace: #0 {main} thrown in /Applications/AMPPS/www/assignment3.com/index.php on line 4.  I'm not sure why this error is happening.  Any ideas?

**Comment by lmerotta-zz** [comment] 2019-03-29 08:46
Hi, could you publish your code on a repository, and give me access to it so I can dig this ? Thanks !

**Comment by command76** [comment] 2019-03-29 14:53
Will do. You should be able to access it.   Here is the URL for the repository.    https://github.com/command76/Projects/tree/master/assignment3.com

**Comment by lmerotta-zz** [comment] 2019-04-01 06:42
The issue is not related to this library. Actually, you are not requiring composer's autoload file, so the namespace PokeAPI is not defined. You can find more details on how to use composer here: https://getcomposer.org/doc/01-basic-usage.md#autoloading

I'll close this issue since it is not part of the library.

**Closed as completed by lmerotta-zz** 2019-04-01 06:42 UTC
